package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ec.edu.sistemalicencias.controller.LoginController;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class LoginView extends JFrame {
    private JPanel panel1;
    private JLabel lblAcceso;
    private JLabel lblUsuario;
    private JTextField txtUser;
    private JLabel lblContraseña;
    private JPasswordField txtPass;
    private JButton btnIngresar;
    private JButton btnSalir;

    private final LoginController loginController;

    public LoginView() {
        this.loginController = new LoginController();

        // Configuración de la ventana
        setTitle("Acceso al Sistema - ANT");
        setContentPane(panel1);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false); // Evita que el usuario deforme el login

        aplicarEstilosYBordes();

        pack(); // Ajusta automáticamente al contenido
        setSize(400, 300); // Tamaño balanceado para los campos
        setLocationRelativeTo(null);

        // Eventos
        btnIngresar.addActionListener(e -> ejecutarLogin());
        btnSalir.addActionListener(e -> System.exit(0));

        // Enter para ingresar automáticamente
        getRootPane().setDefaultButton(btnIngresar);
    }

    private void aplicarEstilosYBordes() {
        // Padding para que los componentes no toquen los bordes de la ventana
        panel1.setBorder(new EmptyBorder(20, 30, 20, 30));
        panel1.setBackground(Color.WHITE);

        // Título Principal
        lblAcceso.setText("INICIAR SESIÓN");
        lblAcceso.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblAcceso.setForeground(new Color(41, 128, 185));
        lblAcceso.setHorizontalAlignment(SwingConstants.CENTER);

        // Fuentes de etiquetas
        Font labelFont = new Font("Segoe UI", Font.PLAIN, 14);
        lblUsuario.setFont(labelFont);
        lblContraseña.setFont(labelFont);

        // Estilo de botones
        btnIngresar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void ejecutarLogin() {
        String usuario = txtUser.getText().trim();
        String clave = new String(txtPass.getPassword());

        if (usuario.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete sus credenciales.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Delegar la autenticación al controlador
        loginController.iniciarSesion(usuario, clave, this);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        lblAcceso = new JLabel();
        lblAcceso.setText("ACCESO AL SISTEMA");
        panel1.add(lblAcceso, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblUsuario = new JLabel();
        lblUsuario.setText("Usuario:");
        panel1.add(lblUsuario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtUser = new JTextField();
        panel1.add(txtUser, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblContraseña = new JLabel();
        lblContraseña.setText("Contraseña:");
        panel1.add(lblContraseña, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPass = new JPasswordField();
        panel1.add(txtPass, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnIngresar = new JButton();
        btnIngresar.setText("Ingresar");
        panel1.add(btnIngresar, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSalir = new JButton();
        btnSalir.setText("Salir");
        panel1.add(btnSalir, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}